name: caller-reusable-approval

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Validating:
    if: github.event_name == 'pull_request' || github.event.ref == 'refs/heads/main'
    uses: vinayprakash893/azure-terraform-actions-reusable/.github/workflows/build.yaml@main
    with:
      environment: production
      terraform_directory: ""
      artifact-name: art-1
    secrets: inherit
      
  Plan:
    name: Deploy to Production
    if: github.event.ref == 'refs/heads/main'
    needs: [Validating]
    # environment: 
    #   name: production
    # steps:
    #   - name: Terraform Initialization
    #     id: terraform-init
    uses: vinayprakash893/azure-terraform-actions-reusable/.github/workflows/plan.yaml@main
    with:
      environment: production
      terraform_directory: ""
      artifact-name: art-1
    secrets: inherit