name: Self-hosted-terrafrom-ssh
on:
  push:
  workflow_dispatch:

jobs:

  Deploy:
    runs-on:  self-hosted
    name: Deploy to Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          #terraform_version: 1.1.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform code
        run: terraform validate

        #     # - name: Plan Terraform changes
  #     #   run: terraform plan
      
  #     # - name: Plan Terraform changes
  #     #   run: terraform apply --auto-approve