name: workflow-to-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:
    uses: vinayprakash893/azure-terraform-actions-reusable/.github/workflows/build.yaml@main
    with:
      environment: dev
      terraform_directory: ""
      artifact-name: 'art-vny-1'
    secrets: inherit

  plancall:
    if: github.event_name == 'pull_request' || github.event.ref == 'refs/heads/main'
    uses: vinayprakash893/azure-terraform-actions-reusable/.github/workflows/plan.yaml@main
    with:
      environment: production
      terraform_directory: ""
      artifact-name: art-vny-1
    secrets: inherit
      
  applycall:
    name: Deploy to Production
    if: github.event.ref == 'refs/heads/main'
    needs: [plancall]
    # environment: 
    #   name: production
    # steps:
    #   - name: Terraform Initialization
    #     id: terraform-init
    uses: vinayprakash893/azure-terraform-actions-reusable/.github/workflows/apply.yaml@main
    with:
      environment: production
      terraform_directory: ""
      artifact-name: art-vny-1
    secrets: inherit